/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author USER
 */
public class GenerateKey extends javax.swing.JFrame {
    
    JPanel pane;

    /**
     * Creates new form GenerateKeyRC5
     */
    public GenerateKey() {
        initComponents();
        pane = PaneMain;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PaneMain = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        txtSecretKey = new javax.swing.JTextField();
        txtDirektoriSimpan = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        rbRC5 = new javax.swing.JRadioButton();
        rbRC6 = new javax.swing.JRadioButton();
        btnGenerate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1060, 550));

        PaneMain.setOpaque(false);
        PaneMain.setPreferredSize(new java.awt.Dimension(1060, 550));
        PaneMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Size");
        PaneMain.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 130, 30));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Algoritma");
        PaneMain.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 130, 30));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Secret Key");
        PaneMain.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 130, 30));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Lokasi");
        PaneMain.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 130, 30));

        txtSize.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtSize.setForeground(new java.awt.Color(204, 204, 204));
        txtSize.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10)));
        txtSize.setCaretColor(new java.awt.Color(255, 255, 255));
        txtSize.setOpaque(false);
        PaneMain.add(txtSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 290, 30));

        txtSecretKey.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtSecretKey.setForeground(new java.awt.Color(204, 204, 204));
        txtSecretKey.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10)));
        txtSecretKey.setCaretColor(new java.awt.Color(255, 255, 255));
        txtSecretKey.setOpaque(false);
        PaneMain.add(txtSecretKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 290, 30));

        txtDirektoriSimpan.setEditable(false);
        txtDirektoriSimpan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDirektoriSimpan.setForeground(new java.awt.Color(204, 204, 204));
        txtDirektoriSimpan.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10)));
        txtDirektoriSimpan.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDirektoriSimpan.setOpaque(false);
        PaneMain.add(txtDirektoriSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 220, 30));

        btnBrowse.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btnBrowse.setForeground(new java.awt.Color(51, 51, 51));
        btnBrowse.setText("Browse");
        btnBrowse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        PaneMain.add(btnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 70, 30));

        buttonGroup1.add(rbRC5);
        rbRC5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        rbRC5.setForeground(new java.awt.Color(204, 204, 204));
        rbRC5.setSelected(true);
        rbRC5.setText("RC5");
        rbRC5.setOpaque(false);
        rbRC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRC5ActionPerformed(evt);
            }
        });
        PaneMain.add(rbRC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, 30));

        buttonGroup1.add(rbRC6);
        rbRC6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        rbRC6.setForeground(new java.awt.Color(204, 204, 204));
        rbRC6.setText("RC6");
        rbRC6.setOpaque(false);
        rbRC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRC6ActionPerformed(evt);
            }
        });
        PaneMain.add(rbRC6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, 30));

        btnGenerate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnGenerate.setForeground(new java.awt.Color(102, 102, 102));
        btnGenerate.setText("Proses");
        btnGenerate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });
        PaneMain.add(btnGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 430, 50));

        jLabel4.setFont(new java.awt.Font("Chocolate Cookies", 1, 56)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Generate Key");
        PaneMain.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1060, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        if (!txtSize.getText().equals("") || !txtSize.getText().equals("") || !txtDirektoriSimpan.getText().equals("")) {
            try {
                File myObj = new File(txtDirektoriSimpan.getText());
                String a = "";
                if (txtDirektoriSimpan.getText().endsWith(".RC5-key")) {
                    a = "RC5";
                 } else {
                    a = "RC6";
                }
                if (myObj.createNewFile()) {
                    System.out.println("File created: " + myObj.getName());
                    JOptionPane.showMessageDialog(this, "Key "+a+" Berhasil Di Buat!");
                }
                FileWriter fw = new FileWriter(myObj.getAbsoluteFile(), false);
                fw.write(txtSize.getText() + " ," + txtSecretKey.getText() + " ," + a);
                fw.close();
            } catch (IOException e) {
                System.out.println("An error occurred.");
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Harap Isi Dengan Benar!");
        }
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        String algoritma = "";
        if (rbRC5.isSelected()) {
            algoritma = "RC5";
        } else {
            algoritma = "RC6";
        }
        JFileChooser fileChooser = new JFileChooser("D:\\") {
            @Override
            public void approveSelection() {
                File f = getSelectedFile();
                if (f.exists() && getDialogType() == SAVE_DIALOG) {
                    int result = JOptionPane.showConfirmDialog(this, "File Sudah Ada, Timpa File?", "Pesan", JOptionPane.YES_NO_OPTION);
                    switch (result) {
                        case JOptionPane.YES_OPTION:
                            super.approveSelection();
                            return;
                        case JOptionPane.NO_OPTION:
                            return;
                        case JOptionPane.CLOSED_OPTION:
                            return;
                    }
                }
                super.approveSelection();
            }
        };
        
        fileChooser.setDialogTitle("Simpan");
        fileChooser.setSelectedFile(new File("GeneratedKey." + algoritma + "-key"));
        fileChooser.setFileFilter(new FileNameExtensionFilter(algoritma + " key File", algoritma + "-key"));
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            if (!fileChooser.getSelectedFile().toString().endsWith(algoritma + "-key")) {
                txtDirektoriSimpan.setText(fileChooser.getSelectedFile().toString() + "." + algoritma + "-key");
            } else {
                txtDirektoriSimpan.setText(fileChooser.getSelectedFile().toString());
            }
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void rbRC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRC6ActionPerformed
        // TODO add your handling code here:
         reset();
    }//GEN-LAST:event_rbRC6ActionPerformed

    private void rbRC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRC5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRC5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateKey().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PaneMain;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnGenerate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton rbRC5;
    private javax.swing.JRadioButton rbRC6;
    private javax.swing.JTextField txtDirektoriSimpan;
    private javax.swing.JTextField txtSecretKey;
    private javax.swing.JTextField txtSize;
    // End of variables declaration//GEN-END:variables
    public void reset() {
        txtDirektoriSimpan.setText("");
    }
}
