package Frame;

import java.awt.Font;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setLocationRelativeTo(null);
        Font f = new Font("CHOCHOLATE COOKIES", Font.PLAIN, 16);
        Font ff = new Font("CHOCHOLATE COOKIES", Font.PLAIN, 18);
        mnOption1.setFont(ff);
        mnOption2.setFont(ff);
        mnGenerateKey.setFont(f);
        mnEnkripsi.setFont(f);
        mnDekripsi.setFont(f);
        mnAnalisis.setFont(f);
        mnMain.setFont(f);
        mnAbout.setFont(f);
        UIManager.put("Menu.font", f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        ParentPane = new javax.swing.JPanel();
        PaneMain1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        MenuBarOption = new javax.swing.JMenuBar();
        mnOption1 = new javax.swing.JMenu();
        mnGenerateKey = new javax.swing.JMenuItem();
        mnEnkripsi = new javax.swing.JMenuItem();
        mnDekripsi = new javax.swing.JMenuItem();
        mnAnalisis = new javax.swing.JMenuItem();
        mnOption2 = new javax.swing.JMenu();
        mnMain = new javax.swing.JMenuItem();
        mnAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RC5 & RC6");
        setResizable(false);

        MainPanel.setOpaque(false);
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ParentPane.setOpaque(false);
        ParentPane.setLayout(new java.awt.CardLayout());

        PaneMain1.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Chocolate Cookies", 1, 56)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Aplikasi Perbandingan Kinerja");

        jLabel7.setFont(new java.awt.Font("Chocolate Cookies", 1, 56)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Algoritma RC5 & RC6");

        javax.swing.GroupLayout PaneMain1Layout = new javax.swing.GroupLayout(PaneMain1);
        PaneMain1.setLayout(PaneMain1Layout);
        PaneMain1Layout.setHorizontalGroup(
            PaneMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
            .addGroup(PaneMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE))
        );
        PaneMain1Layout.setVerticalGroup(
            PaneMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(PaneMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PaneMain1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(3, 3, 3)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ParentPane.add(PaneMain1, "card2");

        MainPanel.add(ParentPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 550));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/background.jpeg"))); // NOI18N
        MainPanel.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 550));

        mnOption1.setText("Option");

        mnGenerateKey.setText("Generate Key");
        mnGenerateKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGenerateKeyActionPerformed(evt);
            }
        });
        mnOption1.add(mnGenerateKey);

        mnEnkripsi.setText("Enkripsi");
        mnEnkripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEnkripsiActionPerformed(evt);
            }
        });
        mnOption1.add(mnEnkripsi);

        mnDekripsi.setText("Dekripsi");
        mnDekripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDekripsiActionPerformed(evt);
            }
        });
        mnOption1.add(mnDekripsi);

        mnAnalisis.setText("Analisis");
        mnAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAnalisisActionPerformed(evt);
            }
        });
        mnOption1.add(mnAnalisis);

        MenuBarOption.add(mnOption1);

        mnOption2.setText("Help");

        mnMain.setText("Main");
        mnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMainActionPerformed(evt);
            }
        });
        mnOption2.add(mnMain);

        mnAbout.setText("About");
        mnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAboutActionPerformed(evt);
            }
        });
        mnOption2.add(mnAbout);

        MenuBarOption.add(mnOption2);

        setJMenuBar(MenuBarOption);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnEnkripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEnkripsiActionPerformed
        // TODO add your handling code here:
        ParentPane.removeAll();
        ParentPane.repaint();
        ParentPane.revalidate();
        Enkripsi pk = new Enkripsi();
        ParentPane.add(pk.pane);
    }//GEN-LAST:event_mnEnkripsiActionPerformed

    private void mnDekripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDekripsiActionPerformed
        // TODO add your handling code here:
        ParentPane.removeAll();
        ParentPane.repaint();
        ParentPane.revalidate();
        Dekripsi pk = new Dekripsi();
        ParentPane.add(pk.pane);
    }//GEN-LAST:event_mnDekripsiActionPerformed

    private void mnAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAnalisisActionPerformed
        // TODO add your handling code here:
        ParentPane.removeAll();
        ParentPane.repaint();
        ParentPane.revalidate();
        Analisis pk = new Analisis();
        ParentPane.add(pk.pane);
    }//GEN-LAST:event_mnAnalisisActionPerformed

    private void mnGenerateKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGenerateKeyActionPerformed
        // TODO add your handling code here:
        ParentPane.removeAll();
        ParentPane.repaint();
        ParentPane.revalidate();
        GenerateKey pk = new GenerateKey();
        ParentPane.add(pk.pane);
    }//GEN-LAST:event_mnGenerateKeyActionPerformed

    private void mnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMainActionPerformed
        // TODO add your handling code here:
        ParentPane.removeAll();
        ParentPane.repaint();
        ParentPane.revalidate();
        GenerateKey pk = new GenerateKey();
        ParentPane.add(PaneMain1);
    }//GEN-LAST:event_mnMainActionPerformed

    private void mnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutActionPerformed
        // TODO add your handling code here:
        ParentPane.removeAll();
        ParentPane.repaint();
        ParentPane.revalidate();
        About pk = new About();
        ParentPane.add(pk.pane);
    }//GEN-LAST:event_mnAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JMenuBar MenuBarOption;
    private javax.swing.JPanel PaneMain1;
    private javax.swing.JPanel ParentPane;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JMenuItem mnAbout;
    private javax.swing.JMenuItem mnAnalisis;
    private javax.swing.JMenuItem mnDekripsi;
    private javax.swing.JMenuItem mnEnkripsi;
    private javax.swing.JMenuItem mnGenerateKey;
    private javax.swing.JMenuItem mnMain;
    private javax.swing.JMenu mnOption1;
    private javax.swing.JMenu mnOption2;
    // End of variables declaration//GEN-END:variables
}
